### ISSUE TITLE
AttributeError: '_regex.Match' object has no attribute 'fuzzy_changes'`

### ISSUE THREAD

**Issue by sdmiller93** [tsailabSJ/changeseq#3]
Hello, 

Trying to run this on two samples. It had been running for a while and then finally errored out after tabulating control merged start positions.

`[06/17 05:27:01PM][ERROR][changeseq] Error identifying off-target cleavage site.
[06/17 05:27:01PM][ERROR][changeseq] Traceback (most recent call last):
  File "/opt/anaconda3/envs/changeseq/bin/changeseq.py", line 189, in findCleavageSites
    identified_sites_file, self.all_chromosomes, merged=self.merged_analysis)
  File "/opt/anaconda3/envs/changeseq/bin/findCleavageSites.py", line 710, in compare
    mismatch_threshold, ga_pval, search_radius, out)
  File "/opt/anaconda3/envs/changeseq/bin/findCleavageSites.py", line 231, in output_alignments
    alignSequences(target_sequence, window_sequence, max_score=mismatch_threshold)
  File "/opt/anaconda3/envs/changeseq/bin/findCleavageSites.py", line 571, in alignSequences
    realigned_target, bulged_offtarget_sequence = realignedSequences(targetsite_sequence, chosen_alignment_b, max_score)
  File "/opt/anaconda3/envs/changeseq/bin/findCleavageSites.py", line 460, in realignedSequences
    substitutions, insertions, deletions = chosen_alignment.fuzzy_changes
AttributeError: '_regex.Match' object has no attribute 'fuzzy_changes'`

**Comment by YichaoOU** [comment]
This is a regex version problem. Upgrade regex will solve the problem. For example `conda install -c conda-forge regex`

Let me know any problem.

Thanks,
Yichao

**Comment by YichaoOU** [comment]
### Update

`conda install -c conda-forge regex` did not work.

`conda install -c anaconda regex=2019.12.9` solved the problem.
